create table bank(bankid int, bankname varchar(30), headoffice varchar(30), branch varchar(30), branchcode int);
insert into bank values(101,'SBI','Delhi','Kottayam',12111);
insert into bank values(102,'Axis','Mumbai','Pala',31122);
insert into bank values(103,'HDFC','Hyderabad','Kochi',41123);
insert into bank values(104,'Union Bank','Banglore','Pala',23333);
insert into bank values(105,'Canara Bank','Chennai','Alappuzha',51121);
commit;
select * from bank;
savepoint A;
delete from bank where bankid=104;
select * from bank;
rollback to savepoint A;
select * from bank;
commit;
select * from bank;
savepoint a;
update bank set branch='Kollam' where bankid=102;
select * from bank;
rollback to savepoint a;
select * from bank;
commit;
select * from bank;
savepoint a;
delete from bank where bankid=103;
select * from bank;
rollback to savepoint a;
select * from bank;
commit;